### ISSUE TITLE
기술 블로그 모음 페이지 반복 현상 이슈

### ISSUE THREAD

**Issue by InSeok9068** [jthcast/techblogposts#1]
안녕하세요. 기술 블로그 잘 보고있습니다. 한가지 문제점이 발생해서 문의드릴려고 합니다.
특정 스크롤이상으로 화면을 내리면 같은 글이 반복적으로 보여지는 현상이 발생합니다. 
저의 경우 2020-03-09일에 게시된 글이 반복적으로 보여집니다.

**Comment by jthcast** [comment]
안녕하세요, 정태훈입니다.

먼저. Techblogposts에 관심을 가져주셔서 정말 감사합니다. 🙇‍♂️
2020-03-09 이후 같은 글만 받아오는 문제점을 확인하였습니다.
최대한 빨리 수정 후 회신 드리겠습니다. 제보 정말 감사합니다!

정태훈 드림

**Comment by jthcast** [comment]
안녕하세요, 정태훈입니다.

문제를 해결한 후 배포 완료하였습니다.
해당 문제는 DB에 저장된 URL들 중 인코딩이 올바르게 되지 않은 경우에서 발생하였습니다.
올바르게 인코딩 되지 않은 URL이 Elasticsearch가 다음 페이지를 불러오는 로직에 오류를 발생시켜 제대로 된 다음 페이지를 불러오지 못했습니다.

예를 들어, 문제가 발생했던 URL은 아래와 같습니다.
https://engineering-skcc.github.io/microservice <https://engineering-skcc.github.io/microservice> inner achitecture/inner-architecture-2/ <https://engineering-skcc.github.io/microservice%20inner%20achitecture/inner-architecture-2/>
올바르게 인코딩 되었다면 아래와 같이 공백문자가 %20 으로 변환되어 저장되었어야 합니다.
https://engineering-skcc.github.io/microservice%20inner%20achitecture/inner-architecture-2/ <https://engineering-skcc.github.io/microservice%20inner%20achitecture/inner-architecture-2/>
하지만 사이트마다 각각 인코딩 여부가 달랐기 때문에 그대로 저장했던 부분에서 해당 문제를 놓쳤습니다.

제보해 주신 덕분에 문제를 인지 후 공백문자를 %20 으로 치환하여 Elasticsearch에 요청을 보내도록 코드를 수정하였습니다.
수정 코드를 보시려면 아래의 링크를 참고해주세요.
https://github.com/jthcast/techblogposts/commit/506f8639ac909c4000fc9b6377fdaca5757763fb <https://github.com/jthcast/techblogposts/commit/506f8639ac909c4000fc9b6377fdaca5757763fb>

앞으로도 문제점 혹은 개선점이 있으시다면 이메일 주시면 반영하도록 노력하겠습니다.
감사합니다.

정태훈 드림

**Comment by jthcast** [comment]
아.. 이슈로 남겨주셨군요!
이슈를 처음 받아봐서 이메일로 답장을 했네요..
답장보낸 이메일을 자동으로 댓글로 달아주는 깃헙이 대단하다고 느꼈습니다.

아무튼 이슈는 해결되었으니 Close 하도록 하겠습니다. 감사합니다.
