### ISSUE TITLE
데보션 블로그 RSS 변경

### ISSUE THREAD

**Issue by ksangki** [jthcast/techblogposts#10]
안녕하세요? 데보션 운영자인데요^^
저희 블로그 RSS가 변경되어서 알려드립니다. 

과거 : https://node2.feed43.com/devocean.xml
신규 : https://node2.feed43.com/skdevocean.xml

참고로 feed43쪽에서 뭔가 서비스를 변경해서 몇일동안 rss가 업데이트가 안되고 있었습니다.

**Comment by jthcast** [comment]
안녕하세요. 정태훈입니다.

먼저, 메일 확인이 늦은점 죄송합니다. 🙇‍♂️
요청주신 '데보션 RSS 주소 변경’을 완료하였습니다.
알려주셔서 감사합니다!

추석은 잘 보내셨는지요, 앞으로도 행복하시길 바라겠습니다.
감사합니다.

정태훈 드림

**Comment by ksangki** [comment]
네, 태훈님 확인했습니다. 감사합니다. ^^

SK telecom Talent | Tech HR팀
***@***.******@***.***> | 010-7154-7600
