### ISSUE TITLE
중복 등록 및 404 Page 이슈

### ISSUE THREAD

**Issue by okyungjin** [jthcast/techblogposts#11]
안녕하세요~
금일 업데이트된 마켓 컬리 포스팅이 중복으로 업로드 되었는데, [상단 포스팅](https://helloworld.kurly.com/blog/166-team-building-game/)은 404 Error가 발생합니다!

![스크린샷 2022-09-27 오후 1 28 21](https://user-images.githubusercontent.com/31913666/192432544-f5a9a3d5-33b1-4ed3-bb3a-6e599dcbf529.png)

좋은 서비스 감사합니다. 잘 사용하고 있습니다 👍

**Comment by jthcast** [comment]
@okyungjin
안녕하세요.

요청주신 중복 데이터 처리를 완료하였습니다!
제보 감사합니다. 좋은 하루 되세요!
