### ISSUE TITLE
저희 블로그 RSS가 변경되었습니다. 

### ISSUE THREAD

**Issue by ksangki** [jthcast/techblogposts#13]
안녕하세요? 데보션 운영자인데요^^
저희 블로그 RSS가 변경되어서 알려드립니다.

과거 : https://node2.feed43.com/skdevocean.xml
현재 : https://bit.ly/devocean_rss

참고로 feed43쪽에서 서비스가 안되어 이전하였습니다.

**Comment by jthcast** [comment]
RSS 주소 수정이 완료되었습니다!
알려주셔서 감사합니다.
