### ISSUE TITLE
기술 블로그 추가 요청

### ISSUE THREAD

**Issue by kgw7401** [jthcast/techblogposts#15]
괜찮은 기술 블로그 하나 추가 요청 드립니다.
오토피디아 https://medium.com/autopedia

**Comment by jthcast** [comment]
안녕하세요. 제안주신 블로그 추가하였습니다.
https://github.com/jthcast/techblogposts/pull/16 에서 확인하실 수 있습니다.

감사합니다.

**Comment by kgw7401** [comment]
빠른 반영 감사합니다😀

**Comment by kgw7401** [comment]
안녕하세요 서비스 잘 이용하고 있습니다
다름이 아니라 해당 블로그의 주소가 바꿔어서 변경 요청 드립니다.
https://blog.doctor-cha.com/

블로그 가장 아래에 보시면 rss도 지원하는 것으로 보입니다

**Comment by jthcast** [comment]
@kgw7401 제보 감사합니다! 말씀해주신 주소와 rss로 수정 반영하였습니다.
