### ISSUE TITLE
[FeatureRequest] RSS

### ISSUE THREAD

**Issue by roeniss** [jthcast/techblogposts#2]
RSS 기능이 있으면 좋을 것 같습니다. 어떻게 생각하시나요? @jthcast

**Comment by jthcast** [comment]
@roeniss 
안녕하세요.

의견 주신 'RSS 기능' 빠른 시일 내 추가해 보도록 하겠습니다.
항상 좋은 의견 주셔서 감사합니다. 😄

**Comment by roeniss** [comment]
긍정적으로 봐주셔서 감사합니다~ @jthcast

**Comment by jthcast** [comment]
@roeniss 
'RSS 기능' 추가 되었습니다.
https://techblogposts.com/rss.xml 에서 확인하실 수 있습니다. 🎉
