### ISSUE TITLE
사명 변경에 따른 기술 블로그명 변경

### ISSUE THREAD

**Issue by Frankle97** [jthcast/techblogposts#20]
안녕하세요~ TechBlogPosts 이용하고 있는 유저입니다.

지마켓 기술 블로그: https://dev.gmarket.com/
![image](https://user-images.githubusercontent.com/61595394/216255423-4c467696-fce7-4082-a2db-99a917bf4467.png)

지마켓글로벌에서 **지마켓**으로 사명이 변경되어서 서비스 내에서도 표기 수정이 가능한지 문의드립니다.

직접 코드 수정해서 PR 요청드리려 했지만 blogs 데이터를 코드 상에서 관리하지는 않는 것으로 보여 Issues 로 올려봅니다~

유용한 서비스 만들어 주셔서 감사합니다 👍

**Comment by jthcast** [comment]
안녕하세요.
요청 주신 '지마켓글로벌을 지마켓으로 변경'이 완료되었습니다.
잘 사용하고 계시다니 저도 기쁘네요 😊
