### ISSUE TITLE
slack에서 feed 를 등록하려고 하니 아래와 같이 feed url이 아니라고 합니다.

### ISSUE THREAD

**Issue by drakejin** [jthcast/techblogposts#24]
### slack에 실행한 명령어

`/feed subscribe https://techblogposts.com/rss.xml`

### 수행한 이후의 결과 화면
<img width="603" alt="image" src="https://github.com/jthcast/techblogposts/assets/10516961/9a8f2b6b-d6ca-4a64-8b60-74792867506b">

**Comment by jthcast** [comment]
적어주신 명령어를 실행하니 잘 동작하는 것 같습니다. 혹시 다시 한 번 시도해 보시겠어요?
RSS피드를 생성할 때 DB에서 현재 생성된 리스트를 가져오는데, 가끔 엘라스틱서치가 뻗을때 제대로 받아오지 못하는 경우가 있습니다.
이 때 오류가 생길 수 있을 것 같습니다. 추후 모니터링 후 뻗을 타이밍에 다시 시도해 보겠습니다.

만약 위 문제라면, 인프라 이슈라 비용문제가 있어 프론트엔드 코드 수정으로 대응하기 힘들 것 같습니다. 😭

<img width="442" alt="스크린샷 2023-05-13 오후 8 10 16" src="https://github.com/jthcast/techblogposts/assets/49227119/13d98b6a-3b9d-476d-a8c5-fdcd9f5b1d2e">
