### ISSUE TITLE
500에러 발생 문의

### ISSUE THREAD

**Issue by dlxotn216** [jthcast/techblogposts#30]
Infinite scroll 도중 아래 요청에서 500에러가 발생하여 다음 포스트 들을 볼수가 없어요ㅜㅜ  

https://techblogposts.com/api/posts?sort=[1690529209000,%22https://blog.bespinglobal.com/post/mysql-mysql-deterministic/?utm_source=rss&utm_medium=rss&utm_campaign=mysql-mysql-deterministic%22]

![image](https://github.com/jthcast/techblogposts/assets/20635638/6e4bf7fc-1c78-4c1f-bd4a-458612132b15)

**Comment by OneTop4458** [comment]
저도 현재 동일한 문제가 발생하네요

**Comment by dlxotn216** [comment]
오늘자로 첫 페이지 진입 시 발생하네요ㅜㅜ..

![image](https://github.com/jthcast/techblogposts/assets/20635638/09ebb763-6426-455f-ab16-639ff84d12a7)

**Comment by dlxotn216** [comment]
오늘자로 다시 발생하는 것 같습니다ㅜㅜ

![image](https://github.com/jthcast/techblogposts/assets/20635638/b0707b29-b9e6-4850-a152-c17c86886962)

**Comment by jthcast** [comment]
안녕하세요, 문제를 인지 하였습니다. 퇴근 후 확인해 보겠습니다 😭

**Comment by jthcast** [comment]
당장은 해결이 어려울 것 같습니다. 최신글이라도 보고 싶으신 분들은 **자동 글 불러오기기능을 해제 해 주세요.**

정확한 이유는 모르겠지만, 로컬에서는 문제가 없고 Vercel에 호스팅 하면 문제가 발생하네요. Vercel에서 제공하는 `ServerlessFunction` 기능이 제가 커서로 사용하기 위해 보내는 `sort`값과 충돌이 있는 것 같습니다. 당장은 해결 하기 어려운 문제 같네요.
지금 너무 바빠서 진행하지 못하고 있지만 예정된 대규모 개선에서 아예 바꿔야 할 듯 합니다 . 😭

**Comment by jthcast** [comment]
우선 에러를 발생시키는 url을 가진 포스트들을 보이지 않도록 설정하였습니다.
해당 문제를 완벽하게 해결하기 전까지 이슈는 유지하겠습니다.

**Comment by bgrooot** [comment]
@jthcast 현재도 이슈가 발생합니다. 원인은 동일한 것 같네요.

**Comment by wonkyDD** [comment]
@jthcast 지금도 이슈 발생하고 있습니다

<img width="703" alt="image" src="https://github.com/jthcast/techblogposts/assets/81248624/d563cee1-b12b-40f0-bff2-294d86799214">

**Comment by jthcast** [comment]
우선 임시 방편으로 아래 작업을 하였습니다.
- 베스핀글로벌 블로그 구독 중단
- 기존 등록되어있던 글들 보여주지 않기

근본적인 문제 해결을 위해서 현재 리팩토링 중입니다. 리팩토링 후 문제가 해결되는지 F/U 하겠습니다!

**Comment by wonkyDD** [comment]
@jthcast  감사합니다. 너무 잘쓰고 있습니다.

**Comment by jthcast** [comment]
우선 포스트들이 오류 없이 잘 보일 수 있도록 리팩토링 하였습니다.

https://github.com/jthcast/techblogposts/pull/36

또 이상이 발생하면 이 이슈를 다시 열어주시거나, 새로운 이슈로 등록해 주시면 f/u 하겠습니다.
