### ISSUE TITLE
rss feed error

### ISSUE THREAD

**Issue by dreamboy1339** [jthcast/techblogposts#31]
슬랙에 RSS 피드를 넣고자 할 때, 아래 링크는 구독이 안됩니다.
https://techblogposts.com/rss.xml

슬랙 가이드 안내에 따라 해당 링크를 검증해보면 문제가 있어 보입니다. 
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftechblogposts.com%2Frss.xml

rss 피드 관련해서 수정 요청 드립니다.

**Comment by jthcast** [comment]
혹시 다시 한 번 시도해 보시겠어요? 문제되는 링크가 포함된 RSS는 잘못된 것으로 판단하는 것 같습니다.
validator에서 에러는 여전히 존재하지만 동작하는지 확인 부탁드립니다!

**Comment by dreamboy1339** [comment]
오늘 확인해보니 등록에 문제가 없었습니다. 👍 
감사합니다.
