### ISSUE TITLE
해외 블로그 추가 문의 

### ISSUE THREAD

**Issue by jamjam0109** [jthcast/techblogposts#4]
안녕하세요 선생님 
덕분에 편하게 기술 블로그를 읽고 있읍니다. 

혹시 해외 블로그도 추가하실 계획은 없으실까요 ? 예를들면 
- https://netflixtechblog.com/
- https://engineering.linkedin.com/blog
- https://engineering.tableau.com/
- https://eng.uber.com/

이런친구들입니다.. 

감사합니다.

**Comment by jthcast** [comment]
@jamjam0109 안녕하세요, techblogposts에 관심을 가져 주셔서 감사합니다.
해외 블로그도 빠른 시일 내 추가할 수 있도록 하겠습니다. 제안 감사합니다!
