### ISSUE TITLE
블로그 추가 문의

### ISSUE THREAD

**Issue by cliearl** [jthcast/techblogposts#6]
안녕하세요 TechBlogPosts 잘 보고 있는 구독자입니다.
이메일로도 보내드렸는데 혹시 못보실까봐 이슈티켓으로도 기술 블로그 추가요청 드립니다. 감사합니다.

- 쿠팡
https://medium.com/coupang-tech/technote/home ->
https://medium.com/coupang-engineering 으로 변경

- 프로그래머스
https://prgms.tistory.com/

- 요기요 기술블로그
https://techblog.yogiyo.co.kr/

- DRAMA&COMPANY
https://blog.dramancompany.com/

- Google Developers Korea Blog
https://developers-kr.googleblog.com/

- 브랜디 랩스 기술 블로그
http://labs.brandi.co.kr/

- ZUM 기술 블로그
https://zuminternet.github.io/

- 사람인HR 기술 블로그
https://saramin.github.io/

- 올리브영 기술블로그
https://tech.oliveyoung.co.kr/

- 강남언니
https://blog.gangnamunni.com/blog

- PRND
https://medium.com/prnd

- 리디북스
https://ridicorp.com/story-category/tech-blog/

- Tecoble
https://tecoble.techcourse.co.kr/

- VCNC Engineering Blog
https://engineering.vcnc.co.kr/

- Bsidesoft co.
https://www.bsidesoft.com/

- Amazon Web Services 한국 블로그
https://aws.amazon.com/ko/blogs/korea/

**Comment by jthcast** [comment]
@cliearl 
안녕하세요. 블로그 제보 주셔서 감사합니다.
아래와 같이 반영하였습니다.

- 추가된 블로그
  - PRND
  - Bsidesoft co.

- 이미 구독중인 블로그
  - 요기요 (딜리버리히어로)
  - DRAMA&COMPANY (드라마앤컴퍼니)
  - Google Developers Korea Blog (구글디벨로퍼스)
  - 브랜디 랩스 기술 블로그 (브랜디)
  - ZUM 기술 블로그 (ZUM)
  - 사람인HR 기술 블로그 (사람인)
  - 리디북스 (리디)
  - VCNC Engineering Blog (VCNC)

- RSS를 지원하지 않아 추가할 수 없는 블로그
  - 올리브영 기술블로그
  - 강남언니

- 영문 블로그라서 추가하지 않은 블로그(추후 지원 예정)
  - 쿠팡

- 추가하지 않은 블로그
  - 프로그래머스
    - 자체 개발에 대한 블로그가 아니며, 타 사용자가 제공한 글을 취사 선택하여 보여주고 있습니다.
  - Tecoble
    - Techblogposts는 기업에서 발행된 검증된 게시물을 보기 위해 만들었습니다. 우아한형제들과 달리, Tecoble은 우아한형제들에서 진행하는 교육프로그램의 수강생 분들께서 적어 주시기 때문에 추가하지 않았습니다. (물론 좋은 글이지만, 프로젝트의 지향점이 다른점 이해 부탁드립니다.)
  - Amazon Web Services 한국 블로그
    - 자체 개발에 대한 블로그가 아니며, 단순 소식을 전하는 블로그로 판단하였습니다.

**Comment by cliearl** [comment]
반영해주셔서 감사합니다!

2022년 5월 27일 (금) 오전 1:07, Taehun Jeong ***@***.***>님이 작성:
