### ISSUE TITLE
기술 블로그 추가 요청

### ISSUE THREAD

**Issue by moonsub-kim** [jthcast/techblogposts#85]
안녕하세요~
아래 기술블로그 추가요청드립니다
https://medium.com/feed/naver-dna-tech-blog

감사합니다!

**Comment by jthcast** [comment]
@moonsub-kim 제보 감사합니다! 제가 메일을 늦게 확인했네요 😭 요청주신 블로그 등록 완료되었습니다!

**Comment by moonsub-kim** [comment]
아닙니다 ㅎㅎ 추가해주시는것만으로도 고맙죠
감사합니다 !!
