### ISSUE TITLE
재 추가요청 드립니다.

### ISSUE THREAD

**Issue by sovirus** [jthcast/techblogposts#91]
좋은 사이트 애용하고 있습니다.

삼성전자 : https://techblog.samsung.com
RSS : https://techblog.samsung.com/rss
와 같이 RSS 를 추가하였습니다.
추가 요청드립니다.

감사합니다. :)

**Comment by jthcast** [comment]
@sovirus 안녕하세요. 해당 RSS로 시도 시 아래와 같은 에러가 발생하고 있습니다.
```
Error: unable to verify the first certificate
code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
```
서버쪽 설정을 확인해 주실 수 있을까요?

**Comment by sovirus** [comment]
혹시 프록시 서버를 거치거나 TLS 버젼을 알 수 있을까요?
저희 허용 TLS 버젼이 1.3 입니다.

**Comment by sovirus** [comment]
위 내용 파악해서 확인해보겠습니다. 감사합니다. :)
